site_name:        "Bayes101.jl"
repo_url:         https://github.com/ubcecon567/Bayes101.jl
site_description: Introduction to Bayesian Estimation
site_author:      Paul Schrimpf
copyright:        Paul Schrimpf

theme:
    name: darkly
    highlightjs: true
       - julia

extra_css:
  - assets/Documenter.css
  - assets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - meta
  - fenced_code
  - smarty
  - toc:
     permalink: True
  - sane_lists
  - admonition
  - footnotes
  - mdx_math
  - attr_list

docs_dir: 'build'

nav:
  - Notes:
    - MCMC sampling methods: ols.md
    - Quasi-Bayesian: quasi.md
  - About:
    - License: license.md
    